### House Price Prediction Pre-Processing

#### Data Collection

In [1]:
import pandas as pd
import sklearn
from pandas import get_dummies

df = pd.read_csv('house_price_prediction.csv')

print(df.head())

  House_ID  Location Property_Type  Bedrooms  Bathrooms  Area_sqft  Age_Years  \
0    H0001  Vadodara     Apartment         3        3.0     1172.0         24
1    H0002     Delhi     Apartment         4        3.0     1599.0         16
2    H0003    Jaipur         Villa         4        4.0     1556.0          4
3    H0004     Surat     Apartment         4        4.0     1664.0          1
4    H0005  Vadodara     Apartment         3        3.0     1514.0          8

   Floor  Total_Floors Parking       Furnished  Balcony  Distance_to_Metro_km  \
0      2             2     Yes       Furnished        3                  10.9
1     13            15     Yes       Furnished        1                   2.8
2      2             7      No  Semi-Furnished        3                  10.0
3      4            11     Yes       Furnished        4                   8.6
4     24            26     Yes  Semi-Furnished        3                  11.6

   Amenities_Score Listed_Date  House_Price
0                5  2023-05-09      4150000
1               10  2025-10-17     12123000
2                8  2024-07-06      8431000
3               10  2025-11-25      6675000
4                8  2023-12-27      5130000

#### Understand Data

In [2]:
print(df.shape)

(2000, 16)

In [3]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   House_ID              2000 non-null   str
 1   Location              2000 non-null   str
 2   Property_Type         2000 non-null   str
 3   Bedrooms              2000 non-null   int64
 4   Bathrooms             1988 non-null   float64
 5   Area_sqft             1988 non-null   float64
 6   Age_Years             2000 non-null   int64
 7   Floor                 2000 non-null   int64
 8   Total_Floors          2000 non-null   int64
 9   Parking               2000 non-null   str
 10  Furnished             1988 non-null   str
 11  Balcony               2000 non-null   int64
 12  Distance_to_Metro_km  1988 non-null   float64
 13  Amenities_Score       2000 non-null   int64
 14  Listed_Date           2000 non-null   str
 15  House_Price           2000 non-null   int64
dtypes: float64(3), int64(7), str(6)
memory usage: 250.1 KB
None

In [4]:
print(df.describe())

          Bedrooms    Bathrooms    Area_sqft   Age_Years        Floor  \
count  2000.000000  1988.000000  1988.000000  2000.00000  2000.000000
mean      2.756000     2.765091  1259.525151    12.73650     8.559500
std       0.965365     1.120630   416.732059     7.43853     6.741675
min       1.000000     1.000000   500.000000     0.00000     1.000000
25%       2.000000     2.000000   954.000000     6.00000     3.000000
50%       3.000000     3.000000  1245.000000    13.00000     7.000000
75%       3.000000     4.000000  1533.250000    19.00000    13.000000
max       5.000000     5.000000  2687.000000    25.00000    30.000000

       Total_Floors      Balcony  Distance_to_Metro_km  Amenities_Score  \
count   2000.000000  2000.000000           1988.000000      2000.000000
mean      16.061000     2.007500              6.268209         6.526500
std        8.214074     1.413663              3.372249         2.275277
min        2.000000     0.000000              0.300000         3.000000
25%        9.000000     1.000000              3.400000         5.000000
50%       16.000000     2.000000              6.200000         7.000000
75%       23.000000     3.000000              9.100000         8.000000
max       30.000000     4.000000             12.000000        10.000000

        House_Price
count  2.000000e+03
mean   7.619256e+06
std    4.033519e+06
min    1.500000e+06
25%    4.739500e+06
50%    6.672000e+06
75%    9.568750e+06
max    3.043800e+07

In [5]:
print(df.dtypes)

House_ID                    str
Location                    str
Property_Type               str
Bedrooms                  int64
Bathrooms               float64
Area_sqft               float64
Age_Years                 int64
Floor                     int64
Total_Floors              int64
Parking                     str
Furnished                   str
Balcony                   int64
Distance_to_Metro_km    float64
Amenities_Score           int64
Listed_Date                 str
House_Price               int64
dtype: object

#### Data Cleaning

In [6]:
# check missing values

print(df.isnull().sum())

House_ID                 0
Location                 0
Property_Type            0
Bedrooms                 0
Bathrooms               12
Area_sqft               12
Age_Years                0
Floor                    0
Total_Floors             0
Parking                  0
Furnished               12
Balcony                  0
Distance_to_Metro_km    12
Amenities_Score          0
Listed_Date              0
House_Price              0
dtype: int64

In [37]:
df['Area_sqft'] = df['Area_sqft'].fillna(df['Area_sqft']).median()

In [7]:
#handle bathrooms missing value

df['Bathrooms'] = df['Bathrooms'].fillna(df['Bathrooms']).median()

In [8]:
#handle furnished missing value

df['Furnished'] = df['Furnished'].fillna(df['Furnished']).mode()[0]

In [9]:
#handle Distance to metrokm missing value

df['Distance_to_Metro_km'] = df['Distance_to_Metro_km'].fillna(df['Distance_to_Metro_km']).mean()

In [38]:
print(df.isnull().sum())

Bedrooms                    0
Bathrooms                   0
Area_sqft                   0
Age_Years                   0
Floor                       0
Total_Floors                0
Parking                     0
Balcony                     0
Distance_to_Metro_km        0
Amenities_Score             0
House_Price                 0
Listed_Year                 0
Listed_Month                0
Location_Bangalore          0
Location_Chennai            0
Location_Delhi              0
Location_Hyderabad          0
Location_Jaipur             0
Location_Mumbai             0
Location_Pune               0
Location_Surat              0
Location_Vadodara           0
Property_Type_Penthouse     0
Property_Type_Row House     0
Property_Type_Villa         0
Area_Per_Bedroom           12
Floor_Ratio                 0
Total_Rooms                 0
Amenities_Per_1000sqft     12
dtype: int64

In [11]:
print(df.head())
print(df.shape)

  House_ID  Location Property_Type  Bedrooms  Bathrooms  Area_sqft  Age_Years  \
0    H0001  Vadodara     Apartment         3        3.0     1172.0         24
1    H0002     Delhi     Apartment         4        3.0     1599.0         16
2    H0003    Jaipur         Villa         4        3.0     1556.0          4
3    H0004     Surat     Apartment         4        3.0     1664.0          1
4    H0005  Vadodara     Apartment         3        3.0     1514.0          8

   Floor  Total_Floors Parking       Furnished  Balcony  Distance_to_Metro_km  \
0      2             2     Yes  Semi-Furnished        3              6.268209
1     13            15     Yes  Semi-Furnished        1              6.268209
2      2             7      No  Semi-Furnished        3              6.268209
3      4            11     Yes  Semi-Furnished        4              6.268209
4     24            26     Yes  Semi-Furnished        3              6.268209

   Amenities_Score Listed_Date  House_Price
0                5  2023-05-09      4150000
1               10  2025-10-17     12123000
2                8  2024-07-06      8431000
3               10  2025-11-25      6675000
4                8  2023-12-27      5130000
(2000, 16)

In [12]:
# check duplicate

print(df.duplicated().sum())
#check duplicate in house_id unique
print(df['House_ID'].duplicated().sum())

0
0

#### Convert Date

In [13]:
df["Listed_Date"] = pd.to_datetime(
    df["Listed_Date"]
)

In [14]:
df["Listed_Year"] = df["Listed_Date"].dt.year

df["Listed_Month"] = df["Listed_Date"].dt.month

In [15]:
#remove orginal date
df.drop("Listed_Date", axis=1, inplace=True)

In [16]:
print(df.head())

  House_ID  Location Property_Type  Bedrooms  Bathrooms  Area_sqft  Age_Years  \
0    H0001  Vadodara     Apartment         3        3.0     1172.0         24
1    H0002     Delhi     Apartment         4        3.0     1599.0         16
2    H0003    Jaipur         Villa         4        3.0     1556.0          4
3    H0004     Surat     Apartment         4        3.0     1664.0          1
4    H0005  Vadodara     Apartment         3        3.0     1514.0          8

   Floor  Total_Floors Parking       Furnished  Balcony  Distance_to_Metro_km  \
0      2             2     Yes  Semi-Furnished        3              6.268209
1     13            15     Yes  Semi-Furnished        1              6.268209
2      2             7      No  Semi-Furnished        3              6.268209
3      4            11     Yes  Semi-Furnished        4              6.268209
4     24            26     Yes  Semi-Furnished        3              6.268209

   Amenities_Score  House_Price  Listed_Year  Listed_Month
0                5      4150000         2023             5
1               10     12123000         2025            10
2                8      8431000         2024             7
3               10      6675000         2025            11
4                8      5130000         2023            12

#### Data Tranform

which columns we have to encode ?

Location
Property_type
Parking
Furnished

In [17]:
# Parking Encode

df["Parking"] = df["Parking"].map({
    "No": 0,
    "Yes": 1
})

In [18]:
print(df['Parking'].head())

0    1
1    1
2    0
3    1
4    1
Name: Parking, dtype: int64

In [19]:
#Encode categorial data

df = pd.get_dummies(
    df,
    columns=[
        "Location",
        "Property_Type",
        "Furnished"
    ],
    drop_first=True,
    dtype=int
)

In [20]:
df.columns.tolist()

['House_ID',
 'Bedrooms',
 'Bathrooms',
 'Area_sqft',
 'Age_Years',
 'Floor',
 'Total_Floors',
 'Parking',
 'Balcony',
 'Distance_to_Metro_km',
 'Amenities_Score',
 'House_Price',
 'Listed_Year',
 'Listed_Month',
 'Location_Bangalore',
 'Location_Chennai',
 'Location_Delhi',
 'Location_Hyderabad',
 'Location_Jaipur',
 'Location_Mumbai',
 'Location_Pune',
 'Location_Surat',
 'Location_Vadodara',
 'Property_Type_Penthouse',
 'Property_Type_Row House',
 'Property_Type_Villa']

In [21]:
print(df["House_Price"].isnull().sum())

0

#### Feature Engineering

In [22]:
# Create Area_Per_Bedroom

df["Area_Per_Bedroom"] = (
    df["Area_sqft"] / df["Bedrooms"]
)
df[["Area_sqft", "Bedrooms", "Area_Per_Bedroom"]].head()

   Area_sqft  Bedrooms  Area_Per_Bedroom
0     1172.0         3        390.666667
1     1599.0         4        399.750000
2     1556.0         4        389.000000
3     1664.0         4        416.000000
4     1514.0         3        504.666667

Area_Per_Bedroom,
Floor_Ratio,
Total_Rooms,
Amenities_Per_1000sqft,
Metro_Access,

In [23]:
# Create Building_Age_Category
df["Age_Category"] = pd.cut(
    df["Age_Years"],
    bins=[-1, 5, 10, 20, 100],
    labels=["New", "Moderate", "Old", "Very_Old"]
)

In [24]:
# Create Floor_Ratio
df["Floor_Ratio"] = (
    df["Floor"] / df["Total_Floors"]
)
df[[
    "Floor",
    "Total_Floors",
    "Floor_Ratio"
]].head()

   Floor  Total_Floors  Floor_Ratio
0      2             2     1.000000
1     13            15     0.866667
2      2             7     0.285714
3      4            11     0.363636
4     24            26     0.923077

In [25]:
# Create Total_Bedrooms_Bathrooms
df["Total_Rooms"] = (
    df["Bedrooms"] + df["Bathrooms"]
)
df[[
    "Bedrooms",
    "Bathrooms",
    "Total_Rooms"
]].head()

   Bedrooms  Bathrooms  Total_Rooms
0         3        3.0          6.0
1         4        3.0          7.0
2         4        3.0          7.0
3         4        3.0          7.0
4         3        3.0          6.0

In [26]:
# Create Amenities_Per_Area
df["Amenities_Per_1000sqft"] = (
    df["Amenities_Score"] / df["Area_sqft"]
) * 1000

df[[
    "Area_sqft",
    "Amenities_Score",
    "Amenities_Per_1000sqft"
]].head()

   Area_sqft  Amenities_Score  Amenities_Per_1000sqft
0     1172.0                5                4.266212
1     1599.0               10                6.253909
2     1556.0                8                5.141388
3     1664.0               10                6.009615
4     1514.0                8                5.284016

In [27]:
#check
print(df.head())

  House_ID  Bedrooms  Bathrooms  Area_sqft  Age_Years  Floor  Total_Floors  \
0    H0001         3        3.0     1172.0         24      2             2
1    H0002         4        3.0     1599.0         16     13            15
2    H0003         4        3.0     1556.0          4      2             7
3    H0004         4        3.0     1664.0          1      4            11
4    H0005         3        3.0     1514.0          8     24            26

   Parking  Balcony  Distance_to_Metro_km  ...  Location_Surat  \
0        1        3              6.268209  ...               0
1        1        1              6.268209  ...               0
2        0        3              6.268209  ...               0
3        1        4              6.268209  ...               1
4        1        3              6.268209  ...               0

   Location_Vadodara  Property_Type_Penthouse  Property_Type_Row House  \
0                  1                        0                        0
1                  0                        0                        0
2                  0                        0                        0
3                  0                        0                        0
4                  1                        0                        0

   Property_Type_Villa  Area_Per_Bedroom  Age_Category  Floor_Ratio  \
0                    0        390.666667      Very_Old     1.000000
1                    0        399.750000           Old     0.866667
2                    1        389.000000           New     0.285714
3                    0        416.000000           New     0.363636
4                    0        504.666667      Moderate     0.923077

   Total_Rooms  Amenities_Per_1000sqft
0          6.0                4.266212
1          7.0                6.253909
2          7.0                5.141388
3          7.0                6.009615
4          6.0                5.284016

[5 rows x 31 columns]

#### Feature Selection

In [28]:
#remove age_category becoz you have age_years

df = df.drop(columns=['Age_Category','House_ID'])

In [29]:
print(df.head())

   Bedrooms  Bathrooms  Area_sqft  Age_Years  Floor  Total_Floors  Parking  \
0         3        3.0     1172.0         24      2             2        1
1         4        3.0     1599.0         16     13            15        1
2         4        3.0     1556.0          4      2             7        0
3         4        3.0     1664.0          1      4            11        1
4         3        3.0     1514.0          8     24            26        1

   Balcony  Distance_to_Metro_km  Amenities_Score  ...  Location_Pune  \
0        3              6.268209                5  ...              0
1        1              6.268209               10  ...              0
2        3              6.268209                8  ...              0
3        4              6.268209               10  ...              0
4        3              6.268209                8  ...              0

   Location_Surat  Location_Vadodara  Property_Type_Penthouse  \
0               0                  1                        0
1               0                  0                        0
2               0                  0                        0
3               1                  0                        0
4               0                  1                        0

   Property_Type_Row House  Property_Type_Villa  Area_Per_Bedroom  \
0                        0                    0        390.666667
1                        0                    0        399.750000
2                        0                    1        389.000000
3                        0                    0        416.000000
4                        0                    0        504.666667

   Floor_Ratio  Total_Rooms  Amenities_Per_1000sqft
0     1.000000          6.0                4.266212
1     0.866667          7.0                6.253909
2     0.285714          7.0                5.141388
3     0.363636          7.0                6.009615
4     0.923077          6.0                5.284016

[5 rows x 29 columns]

Seperate X and y

In [30]:
X = df.drop(columns=['House_Price'])
y = df['House_Price']

In [31]:
print(X.head())

   Bedrooms  Bathrooms  Area_sqft  Age_Years  Floor  Total_Floors  Parking  \
0         3        3.0     1172.0         24      2             2        1
1         4        3.0     1599.0         16     13            15        1
2         4        3.0     1556.0          4      2             7        0
3         4        3.0     1664.0          1      4            11        1
4         3        3.0     1514.0          8     24            26        1

   Balcony  Distance_to_Metro_km  Amenities_Score  ...  Location_Pune  \
0        3              6.268209                5  ...              0
1        1              6.268209               10  ...              0
2        3              6.268209                8  ...              0
3        4              6.268209               10  ...              0
4        3              6.268209                8  ...              0

   Location_Surat  Location_Vadodara  Property_Type_Penthouse  \
0               0                  1                        0
1               0                  0                        0
2               0                  0                        0
3               1                  0                        0
4               0                  1                        0

   Property_Type_Row House  Property_Type_Villa  Area_Per_Bedroom  \
0                        0                    0        390.666667
1                        0                    0        399.750000
2                        0                    1        389.000000
3                        0                    0        416.000000
4                        0                    0        504.666667

   Floor_Ratio  Total_Rooms  Amenities_Per_1000sqft
0     1.000000          6.0                4.266212
1     0.866667          7.0                6.253909
2     0.285714          7.0                5.141388
3     0.363636          7.0                6.009615
4     0.923077          6.0                5.284016

[5 rows x 28 columns]

In [32]:
print(y.name)

House_Price

#### Train Test Split

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

print("X_train:",X_train)
print("X_train_shape:",X_train.shape)
print("X_test:",X_test)
print("X_test_shape:",X_test.shape)
print("y_train:",y_train)
print("y_train_shape:",y_train.shape)
print("y_train:",y_train)
print("y_test:",y_test)
print("y_test_shape:",y_test.shape)
print("y_test:",y_test)

X_train:       Bedrooms  Bathrooms  Area_sqft  Age_Years  Floor  Total_Floors  Parking  \
968          4        3.0     2073.0          3     10            17        1
240          4        3.0     1762.0          7      1            17        1
819          1        3.0      510.0         23     16            26        1
692          3        3.0     1367.0         10     21            28        1
420          2        3.0      999.0          2      6             7        1
...        ...        ...        ...        ...    ...           ...      ...
1130         4        3.0     1921.0          8      8            28        0
1294         3        3.0     1574.0         15      5            13        1
860          2        3.0      949.0         17      2            15        0
1459         3        3.0     1374.0          2      4            24        1
1126         4        3.0     1919.0         12     14            27        1

      Balcony  Distance_to_Metro_km  Amenities_Score  ...  Location_Pune  \
968         2              6.268209                7  ...              0
240         4              6.268209                8  ...              1
819         2              6.268209                4  ...              1
692         3              6.268209                6  ...              0
420         2              6.268209                7  ...              0
...       ...                   ...              ...  ...            ...
1130        3              6.268209                7  ...              0
1294        3              6.268209                7  ...              0
860         0              6.268209                6  ...              0
1459        4              6.268209                8  ...              0
1126        2              6.268209                4  ...              0

      Location_Surat  Location_Vadodara  Property_Type_Penthouse  \
968                0                  0                        0
240                0                  0                        0
819                0                  0                        1
692                1                  0                        0
420                0                  0                        0
...              ...                ...                      ...
1130               0                  0                        0
1294               0                  0                        0
860                0                  0                        0
1459               0                  0                        0
1126               0                  0                        0

      Property_Type_Row House  Property_Type_Villa  Area_Per_Bedroom  \
968                         0                    0        518.250000
240                         0                    0        440.500000
819                         0                    0        510.000000
692                         1                    0        455.666667
420                         0                    0        499.500000
...                       ...                  ...               ...
1130                        1                    0        480.250000
1294                        0                    0        524.666667
860                         0                    0        474.500000
1459                        0                    0        458.000000
1126                        0                    0        479.750000

      Floor_Ratio  Total_Rooms  Amenities_Per_1000sqft
968      0.588235          7.0                3.376749
240      0.058824          7.0                4.540295
819      0.615385          4.0                7.843137
692      0.750000          6.0                4.389173
420      0.857143          5.0                7.007007
...           ...          ...                     ...
1130     0.285714          7.0                3.643935
1294     0.384615          6.0                4.447268
860      0.133333          5.0                6.322445
1459     0.166667          6.0                5.822416
1126     0.518519          7.0                2.084419

[1600 rows x 28 columns]
X_train_shape: (1600, 28)
X_test:       Bedrooms  Bathrooms  Area_sqft  Age_Years  Floor  Total_Floors  Parking  \
1860         2        3.0      669.0         25      4             4        1
353          4        3.0     1692.0         14     25            28        1
1333         3        3.0     1368.0         16      4            17        0
905          3        3.0     1286.0         10     19            23        0
1289         3        3.0     1405.0         25     18            20        1
...        ...        ...        ...        ...    ...           ...      ...
965          3        3.0     1779.0          2      2            20        1
1284         3        3.0     1417.0          6      8            15        1
1739         3        3.0     1112.0          8      2             2        1
261          4        3.0     1969.0         23      1            10        1
535          5        3.0     2490.0         14      8            11        0

      Balcony  Distance_to_Metro_km  Amenities_Score  ...  Location_Pune  \
1860        2              6.268209                6  ...              0
353         3              6.268209                5  ...              0
1333        2              6.268209                9  ...              0
905         3              6.268209                5  ...              0
1289        4              6.268209               10  ...              0
...       ...                   ...              ...  ...            ...
965         3              6.268209                4  ...              0
1284        2              6.268209                8  ...              0
1739        0              6.268209                7  ...              0
261         4              6.268209                4  ...              0
535         2              6.268209                6  ...              0

      Location_Surat  Location_Vadodara  Property_Type_Penthouse  \
1860               0                  0                        0
353                0                  0                        0
1333               0                  0                        1
905                0                  0                        0
1289               0                  0                        0
...              ...                ...                      ...
965                0                  0                        0
1284               1                  0                        1
1739               0                  0                        0
261                0                  0                        0
535                0                  0                        0

      Property_Type_Row House  Property_Type_Villa  Area_Per_Bedroom  \
1860                        1                    0        334.500000
353                         0                    1        423.000000
1333                        0                    0        456.000000
905                         0                    0        428.666667
1289                        0                    0        468.333333
...                       ...                  ...               ...
965                         0                    0        593.000000
1284                        0                    0        472.333333
1739                        0                    1        370.666667
261                         0                    0        492.250000
535                         1                    0        498.000000

      Floor_Ratio  Total_Rooms  Amenities_Per_1000sqft
1860     1.000000          5.0                8.968610
353      0.892857          7.0                2.955083
1333     0.235294          6.0                6.578947
905      0.826087          6.0                3.888025
1289     0.900000          6.0                7.117438
...           ...          ...                     ...
965      0.100000          6.0                2.248454
1284     0.533333          6.0                5.645730
1739     1.000000          6.0                6.294964
261      0.100000          7.0                2.031488
535      0.727273          8.0                2.409639

[400 rows x 28 columns]
X_test_shape: (400, 28)
y_train: 968     10765000
240     11470000
819      3878000
692      4966000
420      7530000
          ...
1130    17033000
1294     7066000
860      8557000
1459     6146000
1126    16855000
Name: House_Price, Length: 1600, dtype: int64
y_train_shape: (1600,)
y_train: 968     10765000
240     11470000
819      3878000
692      4966000
420      7530000
          ...
1130    17033000
1294     7066000
860      8557000
1459     6146000
1126    16855000
Name: House_Price, Length: 1600, dtype: int64
y_test: 1860     3820000
353     10538000
1333    14429000
905      4915000
1289     9589000
          ...
965     14251000
1284     8894000
1739     8098000
261     15926000
535     22084000
Name: House_Price, Length: 400, dtype: int64
y_test_shape: (400,)
y_test: 1860     3820000
353     10538000
1333    14429000
905      4915000
1289     9589000
          ...
965     14251000
1284     8894000
1739     8098000
261     15926000
535     22084000
Name: House_Price, Length: 400, dtype: int64

#### Feature Scaling

In [34]:
print(df.head())

   Bedrooms  Bathrooms  Area_sqft  Age_Years  Floor  Total_Floors  Parking  \
0         3        3.0     1172.0         24      2             2        1
1         4        3.0     1599.0         16     13            15        1
2         4        3.0     1556.0          4      2             7        0
3         4        3.0     1664.0          1      4            11        1
4         3        3.0     1514.0          8     24            26        1

   Balcony  Distance_to_Metro_km  Amenities_Score  ...  Location_Pune  \
0        3              6.268209                5  ...              0
1        1              6.268209               10  ...              0
2        3              6.268209                8  ...              0
3        4              6.268209               10  ...              0
4        3              6.268209                8  ...              0

   Location_Surat  Location_Vadodara  Property_Type_Penthouse  \
0               0                  1                        0
1               0                  0                        0
2               0                  0                        0
3               1                  0                        0
4               0                  1                        0

   Property_Type_Row House  Property_Type_Villa  Area_Per_Bedroom  \
0                        0                    0        390.666667
1                        0                    0        399.750000
2                        0                    1        389.000000
3                        0                    0        416.000000
4                        0                    0        504.666667

   Floor_Ratio  Total_Rooms  Amenities_Per_1000sqft
0     1.000000          6.0                4.266212
1     0.866667          7.0                6.253909
2     0.285714          7.0                5.141388
3     0.363636          7.0                6.009615
4     0.923077          6.0                5.284016

[5 rows x 29 columns]

In [35]:
#Stanadardlization

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df[['Area_sqft','Area_Per_Bedroom','Age_Years']] = scaler.fit_transform(df[['Area_sqft','Area_Per_Bedroom','Age_Years']])
print(df.head())

   Bedrooms  Bathrooms  Area_sqft  Age_Years  Floor  Total_Floors  Parking  \
0         3        3.0  -0.210080   1.514589      2             2        1
1         4        3.0   0.814817   0.438839     13            15        1
2         4        3.0   0.711607  -1.174786      2             7        0
3         4        3.0   0.970832  -1.578193      4            11        1
4         3        3.0   0.610797  -0.636911     24            26        1

   Balcony  Distance_to_Metro_km  Amenities_Score  ...  Location_Pune  \
0        3              6.268209                5  ...              0
1        1              6.268209               10  ...              0
2        3              6.268209                8  ...              0
3        4              6.268209               10  ...              0
4        3              6.268209                8  ...              0

   Location_Surat  Location_Vadodara  Property_Type_Penthouse  \
0               0                  1                        0
1               0                  0                        0
2               0                  0                        0
3               1                  0                        0
4               0                  1                        0

   Property_Type_Row House  Property_Type_Villa  Area_Per_Bedroom  \
0                        0                    0         -0.911534
1                        0                    0         -0.806323
2                        0                    1         -0.930839
3                        0                    0         -0.618102
4                        0                    0          0.408913

   Floor_Ratio  Total_Rooms  Amenities_Per_1000sqft
0     1.000000          6.0                4.266212
1     0.866667          7.0                6.253909
2     0.285714          7.0                5.141388
3     0.363636          7.0                6.009615
4     0.923077          6.0                5.284016

[5 rows x 29 columns]

In [36]:
#Normalization

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[['Area_sqft','Area_Per_Bedroom','Age_Years']] = scaler.fit_transform(df[['Area_sqft','Area_Per_Bedroom','Age_Years']])
print(df.head())

   Bedrooms  Bathrooms  Area_sqft  Age_Years  Floor  Total_Floors  Parking  \
0         3        3.0   0.307270       0.96      2             2        1
1         4        3.0   0.502515       0.64     13            15        1
2         4        3.0   0.482853       0.16      2             7        0
3         4        3.0   0.532236       0.04      4            11        1
4         3        3.0   0.463649       0.32     24            26        1

   Balcony  Distance_to_Metro_km  Amenities_Score  ...  Location_Pune  \
0        3              6.268209                5  ...              0
1        1              6.268209               10  ...              0
2        3              6.268209                8  ...              0
3        4              6.268209               10  ...              0
4        3              6.268209                8  ...              0

   Location_Surat  Location_Vadodara  Property_Type_Penthouse  \
0               0                  1                        0
1               0                  0                        0
2               0                  0                        0
3               1                  0                        0
4               0                  1                        0

   Property_Type_Row House  Property_Type_Villa  Area_Per_Bedroom  \
0                        0                    0          0.164138
1                        0                    0          0.174737
2                        0                    1          0.162194
3                        0                    0          0.193699
4                        0                    0          0.297161

   Floor_Ratio  Total_Rooms  Amenities_Per_1000sqft
0     1.000000          6.0                4.266212
1     0.866667          7.0                6.253909
2     0.285714          7.0                5.141388
3     0.363636          7.0                6.009615
4     0.923077          6.0                5.284016

[5 rows x 29 columns]